# Generated by Django 5.2.1 on 2025-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_notice_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2st Year'), (3, '3st Year'), (4, '4st Year')], default=1),
            preserve_default=False,
        ),
    ]
