# Generated by Django 5.2.1 on 2025-05-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Sem 1'), (2, 'Sem 2'), (3, 'Sem 3'), (4, 'Sem 4'), (5, 'Sem 5'), (6, 'Sem 6'), (7, 'Sem 7'), (8, 'Sem 8')], default=1),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Sem 1'), (2, 'Sem 2'), (3, 'Sem 3'), (4, 'Sem 4'), (5, 'Sem 5'), (6, 'Sem 6'), (7, 'Sem 7'), (8, 'Sem 8')], default=1),
        ),
    ]
